import {
  web,
  mobile,
  social,
  graphic,
  Yussif,
  Hafiz,
  Devine,
  Fati,
  Jeff,
  Zamani,
  facebook,
  instagram,
  twitter,
  email,
  linkedin,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "services",
    title: "Services",
  },
  {
    id: "team",
    title: "Team",
  },
  {
    id: "contact",
    title: "Contact Us",
  },
];

export const services = [
  {
    title: "Web Development",
    icon: web,
    description:
      "Though our expertise in crafting websites and web application, we blend aesthetic elegance with cutting-edge functionality.",
  },
  {
    title: "Mobile Apps",
    icon: mobile,
    description:
      "Though our expertise in crafting mobil apps, we blend aesthetic elegance with cutting-edge functionality.",
  },
  {
    title: "Social Marketting",
    icon: social,
    description:
      "Though our expertise in crafting social media marketting, we blend aesthetic elegance with cutting-edge marketting strategies.",
  },
  {
    title: "Graphic Design",
    icon: graphic,
    description:
      "Though our expertise in crafting UI/UX and graphics, we blend aesthetic elegance with cutting-edge designs.",
  },
];

export const team = [
  {
    image: Fati,
    name: "Abu Fati",
    role: "Front-End Developer",
    email: "email",
    emailUrl: "mailto:example@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "example@gmail.com",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "example@gmail.com",
    linkedinIcon: linkedin,
  },
  {
    image: Hafiz,
    name: "Abdul HaFiz",
    role: "Full Stack Developer",
    email: "email",
    emailUrl: "mailto:example@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "example@gmail.com",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "example@gmail.com",
    linkedinIcon: linkedin,
  },
  {
    image: Devine,
    name: "Devine Debrah Boakye",
    role: "Graphic Designer",
    email: "email",
    emailUrl: "mailto:example@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "example@gmail.com",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "example@gmail.com",
    linkedinIcon: linkedin,
  },
  {
    image: Yussif,
    name: "Yussif Yahuza",
    role: "Full Stack Developer",
    email: "email",
    emailUrl: "mailto:yussifyahuza12@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "https://twitter.com/yussif_yahuza12",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "https://www.linkedin.com/in/yussif-yahuza",
    linkedinIcon: linkedin,
  },
  {
    image: Jeff,
    name: "Nketia Jeffred O.A",
    role: "Content Writter/Researcher",
    email: "email",
    emailUrl: "mailto:example@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "example@gmail.com",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "example@gmail.com",
    linkedinIcon: linkedin,
  },
  {
    image: Zamani,
    name: "Saani Iddris",
    role: "Mobile Developer",
    email: "email",
    emailUrl: "mailto:example@gmail.com",
    emailIcon: email,
    twitter: "twitter",
    twitterUrl: "example@gmail.com",
    twitterIcon: twitter,
    linkedin: "linkedIn",
    linkedinUrl: "example@gmail.com",
    linkedinIcon: linkedin,
  },
];
